Repository rattle-devs/rattle-compiler, pull requests merged in 2021-07, with the labels that each got.

#8 docs(project): issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#7 feat(project): github code analise
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#10 docs(project): Readme additional scopes
  README.md
Labels: documentation

#12 Dev lexer
  CMakeLists.txt
  examples/fib.rattle
  examples/hello_world.rattle
  src/include/token.h
  src/lexer.c
  src/lib/include/utils.h
  src/lib/utils.c
  src/token.c
  src/tpython.c
Labels: todo

#14 refactor(lexer): keywords cleanup
  src/lib/include/utils.h
Labels: enhancement
